import { config } from "dotenv"
config({ path: ".env.local" })

import { PrismaClient } from "@prisma/client"

const db = new PrismaClient()

const users = [
  {
    email: "teste@socion.app",
    name: "Gabriel Teste",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=gabriel",
    headline: "CTO buscando co-fundador de negócios",
    location: "São Paulo, SP",
    availability: "40h/semana (Full Time)",
    investmentRange: "Até R$ 50k",
    businessType: ["SaaS", "IA"],
    desiredRoles: ["Marketing", "Vendas"],
    offeredRoles: ["Tecnologia", "Produto"],
    trustScore: 72, identityScore: 40, experienceScore: 80, competenceScore: 85, reputationScore: 70, commitmentScore: 75, compatibilityScore: 80,
    skills: ["Next.js", "TypeScript", "Product Management", "Node.js"],
  },
  {
    email: "ana.rodrigues@socion.app",
    name: "Ana Rodrigues",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=ana",
    headline: "CMO ex-Nubank, especialista em growth B2C",
    location: "São Paulo, SP",
    availability: "20h/semana (Part Time)",
    investmentRange: "R$ 50k – R$ 200k",
    businessType: ["Fintech", "Marketplace"],
    desiredRoles: ["Tecnologia", "Produto"],
    offeredRoles: ["Marketing", "Vendas"],
    trustScore: 88, identityScore: 90, experienceScore: 95, competenceScore: 85, reputationScore: 80, commitmentScore: 90, compatibilityScore: 85,
    skills: ["Growth Hacking", "Paid Media", "CRM", "Brand Strategy"],
  },
  {
    email: "lucas.ferreira@socion.app",
    name: "Lucas Ferreira",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=lucas",
    headline: "Serial entrepreneur, 2 exits, buscando próximo projeto",
    location: "Florianópolis, SC",
    availability: "40h/semana (Full Time)",
    investmentRange: "R$ 200k – R$ 1M",
    businessType: ["SaaS", "Agritech"],
    desiredRoles: ["Tecnologia", "Operações"],
    offeredRoles: ["Negócios", "Vendas", "Investimento"],
    trustScore: 94, identityScore: 95, experienceScore: 100, competenceScore: 90, reputationScore: 95, commitmentScore: 88, compatibilityScore: 92,
    skills: ["Fundraising", "Sales", "Strategy", "Leadership"],
  },
  {
    email: "mariana.costa@socion.app",
    name: "Mariana Costa",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=mariana",
    headline: "Designer de produto, 8 anos em apps mobile",
    location: "Rio de Janeiro, RJ",
    availability: "30h/semana",
    investmentRange: "Tempo como investimento",
    businessType: ["Consumer", "Healthtech"],
    desiredRoles: ["Tecnologia", "Negócios"],
    offeredRoles: ["Design", "Produto"],
    trustScore: 81, identityScore: 85, experienceScore: 80, competenceScore: 90, reputationScore: 75, commitmentScore: 80, compatibilityScore: 78,
    skills: ["Figma", "UX Research", "Design System", "Prototyping"],
  },
  {
    email: "pedro.alves@socion.app",
    name: "Pedro Alves",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=pedro",
    headline: "CFO & advisor, especialista em estruturação financeira",
    location: "Belo Horizonte, MG",
    availability: "10h/semana (Advisory)",
    investmentRange: "R$ 100k – R$ 500k",
    businessType: ["Fintech", "SaaS", "Edtech"],
    desiredRoles: ["Tecnologia", "Produto", "Marketing"],
    offeredRoles: ["Finanças", "Jurídico", "Investimento"],
    trustScore: 90, identityScore: 95, experienceScore: 90, competenceScore: 85, reputationScore: 92, commitmentScore: 85, compatibilityScore: 88,
    skills: ["M&A", "Financial Modeling", "Fundraising", "Legal"],
  },
  {
    email: "sofia.lima@socion.app",
    name: "Sofia Lima",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=sofia",
    headline: "Engenheira de dados, fundo de IA na FAPESP",
    location: "Campinas, SP",
    availability: "40h/semana (Full Time)",
    investmentRange: "Até R$ 20k",
    businessType: ["IA", "Saúde", "Agritech"],
    desiredRoles: ["Negócios", "Marketing", "Produto"],
    offeredRoles: ["Dados", "IA/ML", "Tecnologia"],
    trustScore: 77, identityScore: 70, experienceScore: 75, competenceScore: 95, reputationScore: 70, commitmentScore: 80, compatibilityScore: 75,
    skills: ["Python", "Machine Learning", "Data Engineering", "LLMs"],
  },
  {
    email: "rafael.santos@socion.app",
    name: "Rafael Santos",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=rafael",
    headline: "Head of Sales, especializado em enterprise SaaS",
    location: "Porto Alegre, RS",
    availability: "40h/semana (Full Time)",
    investmentRange: "Até R$ 30k",
    businessType: ["SaaS", "B2B"],
    desiredRoles: ["Tecnologia", "Produto"],
    offeredRoles: ["Vendas", "Parcerias", "Marketing"],
    trustScore: 83, identityScore: 80, experienceScore: 85, competenceScore: 88, reputationScore: 78, commitmentScore: 85, compatibilityScore: 82,
    skills: ["Enterprise Sales", "CRM", "Outbound", "Partnerships"],
  },
  {
    email: "camila.vieira@socion.app",
    name: "Camila Vieira",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=camila",
    headline: "Médica e empreendedora, fundadora de 2 healthtechs",
    location: "Curitiba, PR",
    availability: "20h/semana (Part Time)",
    investmentRange: "R$ 50k – R$ 150k",
    businessType: ["Healthtech", "Biotech"],
    desiredRoles: ["Tecnologia", "Negócios"],
    offeredRoles: ["Domínio Médico", "Produto", "Regulatório"],
    trustScore: 86, identityScore: 92, experienceScore: 82, competenceScore: 88, reputationScore: 85, commitmentScore: 80, compatibilityScore: 84,
    skills: ["Clinical Ops", "ANVISA", "Healthtech Strategy", "Product"],
  },
  {
    email: "thiago.mendes@socion.app",
    name: "Thiago Mendes",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=thiago",
    headline: "Full-stack dev, open source contributor, ex-VTEX",
    location: "Recife, PE",
    availability: "40h/semana (Full Time)",
    investmentRange: "Tempo como investimento",
    businessType: ["SaaS", "Developer Tools", "IA"],
    desiredRoles: ["Marketing", "Vendas", "Design"],
    offeredRoles: ["Tecnologia", "Infraestrutura"],
    trustScore: 68, identityScore: 55, experienceScore: 72, competenceScore: 88, reputationScore: 62, commitmentScore: 65, compatibilityScore: 70,
    skills: ["React", "Go", "Kubernetes", "API Design"],
  },
  {
    email: "julia.nascimento@socion.app",
    name: "Julia Nascimento",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=julia",
    headline: "COO operacional, escala de 0 a 1 em startups early-stage",
    location: "São Paulo, SP",
    availability: "40h/semana (Full Time)",
    investmentRange: "R$ 20k – R$ 100k",
    businessType: ["Marketplace", "Logistics", "Consumer"],
    desiredRoles: ["Tecnologia", "Produto"],
    offeredRoles: ["Operações", "RH", "Finanças"],
    trustScore: 79, identityScore: 78, experienceScore: 82, competenceScore: 78, reputationScore: 76, commitmentScore: 83, compatibilityScore: 80,
    skills: ["Operations", "OKR", "Process Design", "Team Building"],
  },
]

async function main() {
  for (const u of users) {
    const created = await db.user.upsert({
      where: { email: u.email },
      update: {},
      create: {
        name: u.name,
        email: u.email,
        image: u.image,
        headline: u.headline,
        location: u.location,
        plan: "TRIAL",
        trialEndsAt: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
        availability: u.availability,
        investmentRange: u.investmentRange,
        businessType: u.businessType,
        desiredRoles: u.desiredRoles,
        offeredRoles: u.offeredRoles,
        trustScore: u.trustScore,
        identityScore: u.identityScore,
        experienceScore: u.experienceScore,
        competenceScore: u.competenceScore,
        reputationScore: u.reputationScore,
        commitmentScore: u.commitmentScore,
        compatibilityScore: u.compatibilityScore,
        skills: {
          create: u.skills.map((name) => ({ name, category: "Geral", validated: true })),
        },
        values: {
          create: [
            { question: "Velocidade ou perfeição?", answer: u.trustScore > 80 ? "Perfeição" : "Velocidade" },
            { question: "Risco ou estabilidade?", answer: u.trustScore > 85 ? "Estabilidade" : "Risco" },
            { question: "Crescimento ou lucro?", answer: "Crescimento" },
          ],
        },
      },
    })
    console.log(`✅ ${created.name} (${created.email})`)
  }
}

main().catch(console.error).finally(() => db.$disconnect())
